### ISSUE TITLE
Monitor/workspace Size doesnt respect reserved layout 

### ISSUE THREAD

**Issue by JuicyShark** [zakk4223/hyprNStack#11]
Trying to use addreserved command to hyprland monitor config has Nstack layout not respecting the change. happens in eww dock when it tries to use wlr-roots compositor to reserve space 

monitor=DP-1,5120x1440@120,0x0,1
monitor=DP-1,addreserved,0,0,48,0

Second line is not respected when it is in other layouts.

**Comment by zakk4223** [comment]
Are you using latest source from git? I can't reproduce. Any config section for hyprNStack?

**Comment by zakk4223** [comment]
Maybe try latest git. I found one instance of the reserved space not being used, but it would only have applied to certain configurations of reserved+orientation. Maybe you were running into that.

**Comment by JuicyShark** [comment]
Tried building with the latest git and still have the same issue persisting. 
Have noticed that the reserved space does actually get respected from every direction but where i have a EWW bar coming from 
my nstack config: 
 nstack {
    layout {
      orientation=center
      new_on_top=0
      new_is_master=0
      no_gaps_when_only=0
      special_scale_factor=0.8
      inherit_fullscreen=0
      stacks=4
      center_single_master=1
      mfact=0.43
    }
  }
  
  -- Turns out im a dumb ass and thought i already checked my eww config and it not trying to reserve space itself and never conflicted with other layouts i was using until trying the nstack plugin

**Comment by JuicyShark** [comment]
unable to change orientation to get the windows to respect the screen boundary

**Comment by JuicyShark** [comment]
not entirely sure whats fixed it but after going through some config changes and swapping to hyprland's official plugin manager seemed to resolve the issue
