### ISSUE TITLE
Resizing stacks crash Hyprland

### ISSUE THREAD

**Issue by Heyian** [zakk4223/hyprNStack#20]
My nstack config :
```
nstack {
	layout {
	    orientation=left
	    new_on_top=0
	    new_is_master=0
	    no_gaps_when_only=0
	    special_scale_factor=0.8
	    inherit_fullscreen=1
	    stacks=3
	    center_single_master=0
	    mfact=0
	    single_mfact=0.5
    }

```

Even if I comment out `mfact=0`, Hyprland crashes when I try to resize the stacks. I'd like my stacks to have different width. 

This problem happens with the dispatcher `resizewindow`

I've attached the crash report.
[crash_report.txt](https://github.com/zakk4223/hyprNStack/files/15311522/crash_report.txt)

**Comment by zakk4223** [comment]
Fixed in latest commit

**Comment by Heyian** [comment]
Yep, working fine now. Thanks! 👍

**Comment by bramboomen** [comment]
I seem to have the same issue, I'm on the latest version of nstack.

Using `resizewindow` on the right mouse button I am able to resize the master window, resizing the second stack horizontally does nothing and resizing any tiled window vertically crashes hyprland.

My configuration:
```
    nstack {
        layout {
            orientation = left
            new_on_top = 0
            new_is_master = 0
            no_gaps_when_only = 0
            special_scale_factor = 1
            inherit_fullscreen = 1
            stacks = 2
            center_single_master = 0
            single_mfact = 0.5
        }
    }
```

[Crash report](https://github.com/zakk4223/hyprNStack/files/15377313/hyprlandCrashReport19558.txt)
