### ISSUE TITLE
No bottom gap with >1 window in orientationtop

### ISSUE THREAD

**Issue by iynaix** [zakk4223/hyprNStack#8]
With orientation=top and a bar present, opening 2 or more windows causes the bottom gap to disappear, tested with both stacks=2 and stacks=3, see image below:

![image](https://github.com/zakk4223/hyprNStack/assets/94313/98d9d072-75d0-49ea-a998-9a93114b8084)

The bottom gap works fine when there is only a single window / orientationbottom / no bar present

**Comment by JuicyShark** [comment]
this seems to be related to an issue ive posted about. ive noticed under the hyprnstack recalculateMonitor function makes a constant PFULLWINDOW which grabs a fullscreen window space from a compositor function which does not respect reserved areas and normally placed over the top of them. this issue depends on generally where the user has a bar placed

**Comment by zakk4223** [comment]
Should be fixed. Try latest git please

**Comment by iynaix** [comment]
Yep, it's fixed in the latest release. <3
